// constants.ts — All static data for Guardian Lebanon
// Extracted from App.tsx to prevent bundle-blocking memory crashes

// ─── Types ───────────────────────────────────────────────────────────────────
export type Language = 'en' | 'ar' | 'fr';
export type Theme = 'dark' | 'light';

// ─── Map Defaults ────────────────────────────────────────────────────────────
export const LEBANON_CENTER: [number, number] = [33.8547, 35.8623];
export const INITIAL_CENTER = LEBANON_CENTER; // alias for cross-file compatibility
export const DEFAULT_ZOOM = 8;
export const SAFETY_BUFFER_METERS = 500;
export const OSRM_BASE_URL = 'https://router.project-osrm.org/route/v1/driving';

// ─── Tile Layer URLs ─────────────────────────────────────────────────────────
export const MAP_TILE_URL_DARK = 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png';
export const MAP_TILE_URL_LIGHT = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';

// Bounding box for Lebanon — constrains map pan area
export const LEBANON_BOUNDS: [[number, number], [number, number]] = [
  [32.8, 34.8],  // SW corner
  [34.8, 36.7],  // NE corner
];

// ─── District Coordinates (routing dropdowns) ────────────────────────────────
export const DISTRICT_COORDINATES: Record<string, [number, number]> = {
  dahieh: [33.855, 35.505],
  beirut: [33.8938, 35.5018],
  tyre: [33.2708, 35.1962],
  nabatieh: [33.3789, 35.4839],
  tripoli: [34.4333, 35.8333],
  saida: [33.5631, 35.3689],
  baalbek: [34.0061, 36.2021],
  jounieh: [33.9811, 35.6172],
};

// ─── Emergency Contacts ──────────────────────────────────────────────────────
export const EMERGENCY_CONTACTS = [
  { name: 'LRC Emergency', nameAr: 'طوارئ الصليب الأحمر', nameFr: 'Urgence Croix-Rouge', number: '140', icon: '🏥' },
  { name: 'Civil Defense', nameAr: 'الدفاع المدني', nameFr: 'Défense Civile', number: '125', icon: '🚒' },
  { name: 'ISF', nameAr: 'قوى الأمن', nameFr: 'FSI', number: '112', icon: '👮' },
];

// ─── Filter Chips ────────────────────────────────────────────────────────────
export const FILTER_CATEGORIES = [
  { id: 'all', icon: '📍', en: 'All', ar: 'الكل', fr: 'Tous' },
  { id: 'airstrikes', icon: '💥', en: 'Airstrikes', ar: 'غارات', fr: 'Frappes' },
  { id: 'hospitals', icon: '🏥', en: 'Hospitals', ar: 'مشافي', fr: 'Hôpitaux' },
  { id: 'bakeries', icon: '🍞', en: 'Bakeries', ar: 'أفران', fr: 'Boulangeries' },
  { id: 'pharmacies', icon: '💊', en: 'Pharmacies', ar: 'صيدليات', fr: 'Pharmacies' },
  { id: 'fuel', icon: '⛽', en: 'Fuel', ar: 'وقود', fr: 'Carburant' },
  { id: 'ngo', icon: '🤝', en: 'NGOs', ar: 'منظمات', fr: 'ONG' },
  { id: 'road_status', icon: '🚧', en: 'Roads', ar: 'طرق', fr: 'Routes' },
];

// ─── Service Type Icons ──────────────────────────────────────────────────────
export const SERVICE_ICONS: Record<string, string> = {
  hospital: '🏥', bakery: '🍞', pharmacy: '💊', fuel: '⛽',
  tools: '🔧', ngo: '🤝', food_water: '🍲',
};

// ─── Hospital Fallback (when Overpass API fails) ─────────────────────────────
export const HOSPITAL_FALLBACK: { name: string; coordinates: [number, number]; phone: string }[] = [
  { name: 'AUBMC', coordinates: [33.9, 35.48], phone: '01-350000' },
  { name: 'Hotel Dieu de France', coordinates: [33.882, 35.518], phone: '01-615300' },
  { name: 'Rafik Hariri University Hospital', coordinates: [33.827, 35.495], phone: '01-830000' },
  { name: 'Makassed General Hospital', coordinates: [33.873, 35.513], phone: '01-636000' },
  { name: 'Hammoud Hospital - Saida', coordinates: [33.561, 35.378], phone: '07-720710' },
  { name: 'Nabatieh Govt Hospital', coordinates: [33.378, 35.484], phone: '07-760654' },
  { name: 'Tripoli Governmental Hospital', coordinates: [34.444, 35.837], phone: '06-440172' },
  { name: 'Baalbek Governmental Hospital', coordinates: [34.008, 36.204], phone: '08-370055' },
];

// ─── Translations ────────────────────────────────────────────────────────────
export const TRANSLATIONS: Record<Language, any> = {
  en: {
    name: "Guardian",
    safetyStatus: "Safety Status",
    findSafestPath: "Find Safest Path",
    reportDanger: "Report Danger",
    emergency: "EMERGENCY",
    searchPlaceholder: "Search village, city or address...",
    offlineReady: "Offline Ready",
    liveSafetyFeed: "Live Safety Feed",
    lowBandwidth: "Low Bandwidth Mode",
    optimized3G: "Optimized for 3G networks",
    startPoint: "Start Point",
    destination: "Destination",
    selectDistrict: "Select District",
    report: "REPORT",
    routing: "ROUTING...",
    safePathFound: "Safe Path Found",
    estimatedTime: "Estimated travel time",
    minutes: "min",
    dangerAvoided: "Danger zones avoided",
    lowBandwidthActive: "Low Bandwidth — Tiles Disabled",
    submitReport: "SUBMIT REPORT",
    dangerType: "Select Danger Type",
    details: "Additional Details (Optional)",
    describe: "Describe the situation...",
    noResults: "No results found",
    verified: "Verified",
    nnaVerified: "✓ Verified (NNA)",
    communityReport: "⚠️ Community Report",
    foodWater: "Food/Water Distribution",
    safeCorridor: "Safe Corridor",
    lowPower: "Low Power Mode",
    lowPowerDesc: "Disables map animations to save battery",
    share: "Share Safe Route",
    shareApp: "Share Guardian App",
    shareSuccess: "Link copied to clipboard!",
    welcomeTitle: "Welcome to Guardian",
    welcomeMessage: "Our priority is 'Security over Speed'. We calculate routes based on real-time safety data, not just the shortest distance. Stay safe.",
    settings: "Settings",
    language: "Language",
    theme: "Appearance",
    allResources: "All Resources",
    airstrikes: "Airstrikes",
    hospitals: "Hospitals",
    bakeries: "Bakeries",
    pharmacies: "Pharmacies",
    fuel: "Fuel Stations",
    tools: "Tools",
    ngo: "NGOs/Aid",
    requestAid: "Request Humanitarian Aid",
    aidType: "Aid Type",
    food: "Food",
    medical: "Medical",
    shelter: "Shelter",
    multi: "Multi-Aid",
    hours: "Operational Hours",
    close: "Close",
    understand: "I Understand",
    scanQR: "Scan this code to open Guardian on another device",
    showQR: "Show QR",
    offlineShare: "Share with others offline",
    dangerZone: "DANGER ZONE",
    dangerLevel: "Danger Level",
    airstrike: "Airstrike/Shelling",
    emergencyContacts: "EMERGENCY CONTACTS",
    lrc: "Red Cross",
    civilDefense: "Civil Defense",
    shareLocation: "Share My Location",
    whatsappMessage: "Emergency! My current location is: ",
    verified_ago: "Verified {time} ago",
    reported_ago: "Reported {time} ago",
    userVerified: "Community Verified",
    operational: "Operational",
    limited: "Limited Service",
    closed: "Closed",
    lrcEmergency: "LRC Emergency: 140",
    iAmSafe: "I am Safe",
    iAmSafeMessage: "I am safe! My current location is: ",
    roadStatus: "Road Status",
    roadClosure: "Road Closure",
    verifiedISF: "✓ Verified (ISF)",
    communityAlert: "⚠️ Community Alert",
    stillClosed: "Still Closed",
    roadNowOpen: "Road is Open",
    verifiedBy: "Verified by {count} users",
    communityVote: "Community Vote",
    earthquakes: "Earthquakes",
    seismicAlert: "SEISMIC ALERT",
    seismicInstructions: "Drop, Cover, and Hold On",
    magnitude: "Magnitude",
    richter: "Richter",
    workingOffline: "Working Offline",
    survivalGuide: "Survival Guide",
    earthquakeSafety: "Earthquake Safety",
    gasLeakSafety: "Gas Leak Safety",
    gasLeakInstructions: "If you smell gas: Open windows, do not use switches, leave immediately.",
    safetyDisclaimerTitle: "Safety Disclaimer",
    safetyDisclaimerMessage: "This app provides safety data for informational purposes only. Always prioritize local authorities' instructions. Stay safe.",
    videoCall: "Video Call",
    shareCallLink: "Share Call Link",
    hangUp: "Hang Up",
    emergencyVideoCall: "Emergency Video Call",
    districts: {
      dahieh: "Dahieh", beirut: "Beirut", tyre: "Tyre", nabatieh: "Nabatieh",
      tripoli: "Tripoli", saida: "Saida", baalbek: "Baalbek", jounieh: "Jounieh"
    }
  },
  ar: {
    name: "الحارس",
    safetyStatus: "حالة الأمان",
    reportDanger: "بلغ عن خطر",
    emergency: "طوارئ",
    searchPlaceholder: "ابحث عن قرية، مدينة أو عنوان...",
    offlineReady: "جاهز للعمل دون اتصال",
    liveSafetyFeed: "بلاغات الأمان المباشرة",
    lowBandwidth: "وضع النطاق الترددي المنخفض",
    optimized3G: "محسن لشبكات 3G",
    startPoint: "نقطة البداية",
    destination: "الوجهة",
    selectDistrict: "اختر المنطقة",
    report: "تبليغ",
    routing: "جاري التوجيه...",
    safePathFound: "تم العثور على مسار آمن",
    estimatedTime: "الوقت المقدر",
    minutes: "دقيقة",
    dangerAvoided: "تم تجنب مناطق الخطر",
    lowBandwidthActive: "نطاق منخفض — الخرائط معطلة",
    submitReport: "إرسال التقرير",
    dangerType: "اختر نوع الخطر",
    details: "تفاصيل إضافية (اختياري)",
    describe: "صف الموقف...",
    noResults: "لم يتم العثور على نتائج",
    verified: "تم التحقق",
    nnaVerified: "موثوق (NNA) ✓",
    communityReport: "بلاغ مجتمعي ⚠️",
    foodWater: "توزيع طعام/ماء",
    safeCorridor: "ممر آمن",
    lowPower: "وضع توفير الطاقة",
    lowPowerDesc: "يعطل الرسوم المتحركة لتوفير البطارية",
    share: "مشاركة الطريق الآمن",
    shareApp: "مشاركة تطبيق الحارس",
    shareSuccess: "تم نسخ الرابط!",
    welcomeTitle: "مرحباً بك في الحارس",
    welcomeMessage: "أولويتنا هي 'الأمان قبل السرعة'. نقوم بحساب الطرق بناءً على بيانات الأمان في الوقت الفعلي، وليس فقط المسافة الأقصر. ابقَ آمناً.",
    settings: "الإعدادات",
    language: "اللغة",
    theme: "المظهر",
    allResources: "جميع الموارد",
    airstrikes: "غارات جوية",
    hospitals: "مشافي",
    bakeries: "أفران",
    pharmacies: "صيدليات",
    fuel: "محطات وقود",
    tools: "أدوات",
    ngo: "منظمات",
    requestAid: "طلب مساعدات إنسانية",
    aidType: "نوع المساعدة",
    food: "طعام",
    medical: "طبي",
    shelter: "مأوى",
    multi: "مساعدات متعددة",
    hours: "ساعات العمل",
    close: "إغلاق",
    understand: "أفهم ذلك",
    scanQR: "امسح هذا الرمز لفتح الحارس على جهاز آخر",
    showQR: "عرض الرمز",
    offlineShare: "مشاركة مع الآخرين دون اتصال",
    dangerZone: "منطقة خطر",
    dangerLevel: "مستوى الخطر",
    airstrike: "غارة جوية / قصف",
    emergencyContacts: "جهات اتصال الطوارئ",
    lrc: "الصليب الأحمر",
    civilDefense: "الدفاع المدني",
    shareLocation: "مشاركة موقعي",
    whatsappMessage: "طوارئ! موقعي الحالي هو: ",
    verified_ago: "تم التحقق منذ {time}",
    reported_ago: "تم التبليغ منذ {time}",
    userVerified: "تم التحقق من المجتمع",
    operational: "قيد الخدمة",
    limited: "خدمة محدودة",
    closed: "مغلق",
    lrcEmergency: "طوارئ الصليب الأحمر: ١٤٠",
    iAmSafe: "أنا بخير",
    iAmSafeMessage: "أنا بخير! موقعي الحالي هو: ",
    findSafestPath: "البحث عن المسار الأكثر أماناً",
    roadStatus: "حالة الطرق",
    roadClosure: "إغلاق طريق",
    verifiedISF: "موثوق (ISF) ✓",
    communityAlert: "بلاغ مجتمعي ⚠️",
    stillClosed: "لا يزال مغلقاً",
    roadNowOpen: "الطريق مفتوح",
    verifiedBy: "تم التحقق من {count} مستخدم",
    communityVote: "تصويت المجتمع",
    earthquakes: "هزات أرضية",
    seismicAlert: "تنبيه زلزالي",
    seismicInstructions: "انخفض، تغطَّ، وتمسك",
    magnitude: "القوة",
    richter: "ريختر",
    workingOffline: "نظام عدم الاتصال",
    survivalGuide: "دليل النجاة",
    earthquakeSafety: "السلامة من الزلازل",
    gasLeakSafety: "السلامة من تسرب الغاز",
    gasLeakInstructions: "إذا شممت رائحة غاز: افتح النوافذ، لا تستخدم المفاتيح الكهربائية، وغادر فوراً.",
    safetyDisclaimerTitle: "إخلاء مسؤولية الأمان",
    safetyDisclaimerMessage: "يوفر هذا التطبيق بيانات الأمان لأغراض إعلامية فقط. أعطِ الأولوية دائماً لتعليمات السلطات المحلية. ابقَ آمناً.",
    videoCall: "اتصال فيديو",
    shareCallLink: "مشاركة رابط المكالمة",
    hangUp: "إنهاء المكالمة",
    emergencyVideoCall: "اتصال فيديو الطوارئ",
    districts: {
      dahieh: "الضاحية", beirut: "بيروت", tyre: "صور", nabatieh: "النبطية",
      tripoli: "طرابلس", saida: "صيدا", baalbek: "بعلبك", jounieh: "جونية"
    }
  },
  fr: {
    name: "Le Gardien",
    safetyStatus: "État de Sécurité",
    findSafestPath: "Trouver le chemin le plus sûr",
    reportDanger: "Signaler un danger",
    emergency: "Urgences",
    searchPlaceholder: "Chercher un village, ville...",
    offlineReady: "Prêt Hors Ligne",
    liveSafetyFeed: "Signalements en Direct",
    lowBandwidth: "Mode Basse Bande",
    optimized3G: "Optimisé pour la 3G",
    startPoint: "Point de Départ",
    destination: "Destination",
    selectDistrict: "Sélectionner District",
    report: "SIGNALER",
    routing: "CALCUL...",
    safePathFound: "Chemin Sûr Trouvé",
    estimatedTime: "Temps de trajet estimé",
    minutes: "min",
    dangerAvoided: "Zones dangereuses évitées",
    lowBandwidthActive: "Basse Bande — Tuiles Désactivées",
    submitReport: "ENVOYER LE RAPPORT",
    dangerType: "Type de Danger",
    details: "Détails (Optionnel)",
    describe: "Décrivez la situation...",
    noResults: "Aucun résultat",
    verified: "Vérifié",
    nnaVerified: "✓ Vérifié (NNA)",
    communityReport: "⚠️ Signalement Communautaire",
    foodWater: "Distribution Eau/Nourriture",
    safeCorridor: "Corridor Sûr",
    lowPower: "Mode Économie",
    lowPowerDesc: "Désactive les animations pour économiser la batterie",
    share: "Partager l'itinéraire",
    shareApp: "Partager l'application",
    shareSuccess: "Lien copié!",
    welcomeTitle: "Bienvenue sur Le Gardien",
    welcomeMessage: "Notre priorité est 'La Sécurité avant la Vitesse'. Nous calculons les itinéraires basés sur la sécurité en temps réel, pas seulement la distance. Restez en sécurité.",
    settings: "Paramètres",
    language: "Langue",
    theme: "Apparence",
    allResources: "Toutes les ressources",
    airstrikes: "Frappes Aériennes",
    hospitals: "Hôpitaux",
    bakeries: "Boulangeries",
    pharmacies: "Pharmacies",
    fuel: "Stations-service",
    tools: "Outils",
    ngo: "ONG",
    requestAid: "Demander de l'aide humanitaire",
    aidType: "Type d'aide",
    food: "Nourriture",
    medical: "Médical",
    shelter: "Abri",
    multi: "Aide multiple",
    hours: "Heures d'ouverture",
    close: "Fermer",
    understand: "Je comprends",
    scanQR: "Scannez ce code pour ouvrir Le Gardien sur un autre appareil",
    showQR: "Afficher le QR",
    offlineShare: "Partager hors ligne",
    dangerZone: "ZONE DE DANGER",
    dangerLevel: "Niveau de Danger",
    airstrike: "Frappe Aérienne / Bombardement",
    emergencyContacts: "CONTACTS D'URGENCE",
    lrc: "Croix-Rouge",
    civilDefense: "Défense Civile",
    shareLocation: "Partager ma position",
    whatsappMessage: "Urgence ! Ma position actuelle est : ",
    verified_ago: "Vérifié il y a {time}",
    reported_ago: "Signalé il y a {time}",
    userVerified: "Vérifié par la Communauté",
    operational: "Opérationnel",
    limited: "Service Limité",
    closed: "Fermé",
    lrcEmergency: "Urgence Croix-Rouge: 140",
    iAmSafe: "Je suis en sécurité",
    iAmSafeMessage: "Je suis en sécurité ! Ma position actuelle est : ",
    roadStatus: "État des Routes",
    roadClosure: "Route Fermée",
    verifiedISF: "✓ Vérifié (ISF)",
    communityAlert: "⚠️ Alerte Communautaire",
    stillClosed: "Toujours Fermée",
    roadNowOpen: "Route Ouverte",
    verifiedBy: "Vérifié par {count} utilisateurs",
    communityVote: "Vote Communautaire",
    earthquakes: "Séismes",
    seismicAlert: "ALERTE SISMIQUE",
    seismicInstructions: "Baissez-vous, abritez-vous et agrippez-vous",
    magnitude: "Magnitude",
    richter: "Richter",
    workingOffline: "Mode Hors-ligne",
    survivalGuide: "Guide de Survie",
    earthquakeSafety: "Sécurité Séisme",
    gasLeakSafety: "Sécurité Fuite de Gaz",
    gasLeakInstructions: "Si vous sentez du gaz : ouvrez les fenêtres, n'utilisez pas d'interrupteurs, partez immédiatement.",
    safetyDisclaimerTitle: "Avis de sécurité",
    safetyDisclaimerMessage: "Cette application fournit des données de sécurité à titre informatif uniquement. Priorisez toujours les instructions des autorités locales. Restez en sécurité.",
    videoCall: "Appel Vidéo",
    shareCallLink: "Partager le lien",
    hangUp: "Raccrocher",
    emergencyVideoCall: "Appel Vidéo d'Urgence",
    districts: {
      dahieh: "Dahieh", beirut: "Beyrouth", tyre: "Tyr", nabatieh: "Nabatieh",
      tripoli: "Tripoli", saida: "Saïda", baalbek: "Baalbek", jounieh: "Jounieh"
    }
  }
};

// ─── Danger Types ────────────────────────────────────────────────────────────
export const DANGER_TYPES: Record<Language, string[]> = {
  en: ["Airstrike/Shelling", "Road Block", "Gunfire", "Checkpoint", "Resource Update", "Request Humanitarian Aid"],
  ar: ["غارة جوية / قصف", "قطع طريق", "إطلاق نار", "حاجز أمني", "تحديث الموارد", "طلب مساعدات إنسانية"],
  fr: ["Frappe Aérienne / Bombardement", "Barrage Routier", "Fusillade", "Point de Contrôle", "Mise à jour des ressources", "Demande d'aide humanitaire"]
};
